name: doccheck
on:
  push:

jobs:
  doccheck:
    name: Documentation Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Check documentation
        uses: mathiasvr/command-output@6309e0ee6ed594fd7f382bd826e138e0ba04dd63
        with:
          run: python3 tools/doccheck.py asm/LILLY.asm
        id: doccheck
      - name: Unlock issue
        run: gh issue unlock https://github.com/NexusSfan/lillydecomp/issues/2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: 3478184596
          body: ${{ steps.doccheck.outputs.stdout }}
          token: ${{ secrets.GITHUB_TOKEN }}
          edit-mode: replace
      - name: Lock issue
        run: gh issue lock https://github.com/NexusSfan/lillydecomp/issues/2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
